### ISSUE TITLE
create-xp-app new MyAwesomeProject error

### ISSUE THREAD

**Issue by ASCE1885** [react-native-training/create-xp-app#1]
➜  react-native-workspace create-xp-app new MyAwesomeProject
module.js:442
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/create-xp-app/bin/cli.js:3:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by dabit3** [comment]
Hello! Can you tell me what version of Node you are running as well as what OS you are on? Thanks.

**Comment by ASCE1885** [comment]
@dabit3 hi,my node version is v6.2.2,os version is OS X EI Capitan 10.11.6,thanks!

**Comment by dabit3** [comment]
@ASCE1885 just pushed new updated and this should be fixed!
