### ISSUE TITLE
"code":"EMFILE","errno":"EMFILE","syscall":"Error watching file for changes:","filename":null

### ISSUE THREAD

**Issue by sunfmin** [react-native-training/create-xp-app#10]
Create a new app, and `npm run start` gives the following error

```
Loading dependency graph...
React packager ready.

2017-06-30 13:19 node[50482] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-06-30 13:19 node[50482] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
 ERROR  Error watching file for changes: EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"Error watching file for changes:","filename":null}
Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1050:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1374:11)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 11
npm ERR! rxp@1.0.0 start: `node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 11
npm ERR! 
npm ERR! Failed at the rxp@1.0.0 start script 'node node_modules/react-native/local-cli/cli.js start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rxp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/react-native/local-cli/cli.js start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rxp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rxp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sunfmin/.npm/_logs/2017-06-30T05_19_34_238Z-debug.log

```

**Comment by dabit3** [comment]
Thanks @sunfmin I'll take a look at this.

**Comment by dabit3** [comment]
We've been unable to produce this! If you still are having trouble, please reach out to me dabit3@gmail.com and I will do my best to help out.
