### ISSUE TITLE
It is not working

### ISSUE THREAD

**Issue by iamjesse98** [react-native-training/create-xp-app#13]
>create-xp-app simplePro
----------------------------------------------------------
child_process.js:380
    throw new TypeError('"file" argument must be a non-empty string');
    ^

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:380:11)
    at exports.spawn (child_process.js:485:38)
    at Object.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\create-xp-app\bin\cli.js:16:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)

**Comment by dabit3** [comment]
Hey @iamjesse98 , are you still getting this error? Please try installing the newest version of the cli, hopefully this will no longer be an issue. thanks.
